filters:
    comments: true
    allowlist:
        allowlistConfigPaths:
            - allow.yml

plugins:
    - review

rules:
    preset-ja-technical-writing:
        ja-no-mixed-period:
            periodMark: "．"
        max-ten:
            touten: "，"
            kuten: "．"
    prh:
        rulePaths:
            - "./prh.yml"
            