version: "3"
services:
    redpen:
        build:
            context: ./redpen-docker
        volumes:
            - ./:/root/project_root
            - tmp:/tmp
        stdin_open: true

    review:
        build:
            context: ./review-docker
        volumes:
            - ./:/root/project_root
        stdin_open: true

    docker-langserver:
        image: rcjsuen/docker-langserver
        volumes:
            - ./:/root/project_root
        stdin_open: true
        entrypoint: /bin/ash

    main:
        build:
            context: ./neovim-docker
            args:
                cmds:
                    ${COMPOSE_PROJECT_NAME}_redpen_1:redpen
                    ${COMPOSE_PROJECT_NAME}_review_1:rake
                    ${COMPOSE_PROJECT_NAME}_docker-langserver_1:/docker-langserver/bin/docker-langserver
        volumes:
            - ./:/root/project_root
            - /var/run/docker.sock:/var/run/docker.sock
            - ./coc-settings.json:/root/.config/nvim/coc-settings.json
            - tmp:/tmp
        stdin_open: true
        working_dir: /root/project_root

volumes:
    tmp:
