version: "3.4"

volumes:
    shared_bin:
    tmp:
    vscode-server:

x-common-options: &common-options
    user: ${UID:-0}:${GID:-0}
    depends_on:
        - scripts
    environment:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-review-template}
        MOUNT_WAIT_COMMAND: until [ -d .devcontainer ]; do :; done
        LAUNCH_COMMAND: >-
            sudo find /root/shared_bin/ -type f | xargs -I {} basename {} | xargs -I {} sh -c '
            if ! command -v {}; then sudo cp /root/shared_bin/{} /usr/local/bin/{} && sudo chmod +s /usr/local/bin/{}; fi
            ' &&
            sleep infinity
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${PROJECT_ROOT:-/var/lib/docker/volumes/vsc-remote-containers/_data/review-template}/:/workspaces/review-template
        - shared_bin:/root/shared_bin
        - tmp:/tmp
        - vscode-server:/root/.vscode-server/bin
    working_dir: /workspaces/review-template
    command: sh -c 'eval $${MOUNT_WAIT_COMMAND} && eval $${LAUNCH_COMMAND}'

services:
    docker:
        build: ./.devcontainer/docker-docker
        volumes:
            - shared_bin:/root/shared_bin
        command: sh -c 'cp -f `which docker` /root/shared_bin/docker && sleep infinity'

    scripts:
        image: bash
        <<: *common-options
        depends_on:
            - docker
        user: root # needed for generate_docker_cmd.sh
        command: >-
            sh -c '
            eval $${MOUNT_WAIT_COMMAND} &&
            bash .devcontainer/generate_docker_cmd.sh /root/shared_bin
            nvim@neovim
            tmux@tmux
            git@git
            git-shell@git
            fish@tmux
            rake@review
            npm@node
            npx@node
            '

    node:
        build: ./.devcontainer/node-docker
        <<: *common-options
        # Install textlint packages.
        # Packages are configured in ./package.json.
        command: >-
            sh -c 'eval $${MOUNT_WAIT_COMMAND} && npm install && eval $${LAUNCH_COMMAND}'

    review:
        build: ./.devcontainer/review-docker
        <<: *common-options
        # Change owner of VS Code's directory.
        command: >-
            sh -c '
            eval $${MOUNT_WAIT_COMMAND} &&
            sudo chown `id -u`:`id -g` /root/.vscode-server &&
            sudo chown `id -u`:`id -g` /root/.vscode-server/bin &&
            sudo usermod --shell /usr/local/bin/fish `whoami` &&
            eval $${LAUNCH_COMMAND}
            '

    tmux:
        build: ./.devcontainer/tmux-docker
        <<: *common-options

    git:
        build: ./.devcontainer/git-docker
        <<: *common-options

    neovim:
        build:
            context: ./.devcontainer/neovim-docker
            args:
                EXTRA_COC_PLUGINS: coc-docker
        <<: *common-options
