version: "3.4"

volumes:
    tmp:
    vscode-server:

x-common-options: &common-options
    user: ${UID:-0}:${GID:-0}
    depends_on:
        - docker
    environment:
        PREPARE_COMMAND: |
            # wait for mounting the volumes
            until [ -d /root/.vscode-server ]; do :; done
            sleep 1

            # prepare docker command
            ln -sf /tmp/shared_bin/docker /usr/local/bin/

            # prepare other commands
            container_commands='
                nvim@neovim
                tmux@tmux
                git@git
                git-shell@git
                fish@tmux
                rake@review
                review-update@review
                npm@node
                npx@node
            '
            for container_command in `echo $$container_commands | tr -s ' ' '\n'`; do
                command_name=`echo $$container_command | cut -d '@' -f 1`
                service_name=`echo $$container_command | cut -d '@' -f 2`

                if command -v $$command_name; then continue; fi

                { \
                    echo '#!/bin/sh -e'; \
                    echo 'if [ -t 1 ]; then tty_option=-t; fi'; \
                    echo 'exec docker exec -i $$tty_option -w $$PWD '"${COMPOSE_PROJECT_NAME}_$${service_name}_1 $${command_name}"' "$$@"'; \
                } > /usr/local/bin/$$command_name
                sudo chmod +x /usr/local/bin/$$command_name
            done
        LAUNCH_COMMAND: |
            if [ -z "${COMPOSE_PROJECT_NAME}" ]; then
                # exit if the project name is undetermined
                docker rm -f $$HOSTNAME
            fi
            sleep infinity
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${WORKSPACE_ROOT:-../../}:/workspaces
        - tmp:/tmp
        - vscode-server:/root/.vscode-server/bin
    working_dir: /workspaces/${PROJECT_FOLDER}
    command:
        - sh
        - -cex
        - |
            eval "$${PREPARE_COMMAND}"
            eval "$${LAUNCH_COMMAND}"

services:
    docker:
        build: ./docker-docker
        image: splascope/docker-docker
        volumes:
            - tmp:/tmp
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - sh
            - -cex
            - |
                mkdir -p /tmp/shared_bin
                cp -f `which docker` /tmp/shared_bin/docker
                docker rm -f $$HOSTNAME

    node:
        build: ./node-docker
        image: splascope/node-docker
        <<: *common-options
        # Install textlint packages.
        # Packages are configured in ./package.json.
        command:
            - sh
            - -cex
            - |
                eval "$${PREPARE_COMMAND}"
                npm install
                eval "$${LAUNCH_COMMAND}"

    review:
        build: ./review-docker
        image: splascope/review-docker
        <<: *common-options
        command:
            - sh
            - -ecx
            - |
                sudo chown -R `id -u`:`id -g` /root
                eval "$${PREPARE_COMMAND}"

                container_volume_name=`docker inspect --format='{{ index .Config.Labels "vsch.local.repository.volume"}}' $$HOSTNAME`
                project_folder_name=`docker inspect --format='{{ index .Config.Labels "com.docker.compose.project.working_dir"}}' $$HOSTNAME | sed -r 's/^.+\/(.+)\/.+$$/\1/'`
                cd /workspaces/$$project_folder_name

                # make .env
                { \
                    echo "# AUTO GENERATED FILE"; \
                    echo "# DO NOT MODIFY THIS FILE"; \
                    echo "UID=$$(ls -nld . | awk '{print $$3}')"; \
                    echo "GID=$$(ls -nld . | awk '{print $$4}')"; \
                    if [ -n "$$container_volume_name" ]; then \
                        echo "WORKSPACE_ROOT=/var/lib/docker/volumes/$$container_volume_name/_data"; \
                    fi; \
                    echo "PROJECT_FOLDER=$$project_folder_name"; \
                    echo "COMPOSE_PROJECT_NAME=$${container_volume_name:-local}_$${project_folder_name}"; \
                } > .env

                eval "$${LAUNCH_COMMAND}"

    tmux:
        build: ./tmux-docker
        image: splascope/tmux-docker
        <<: *common-options

    git:
        build: ./git-docker
        image: splascope/git-docker
        <<: *common-options

    neovim:
        build: ./neovim-docker
        image: splascope/neovim-docker
        <<: *common-options
